server.port=8083
spring.application.name=appointment-service

# Kết nối PostgreSQL (Cần tạo sẵn DB appointment_db)
spring.datasource.url=jdbc:postgresql://localhost:5432/appointment_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
